name: Import Algosec Risk
on:
  push:
    branches: ["main"]

jobs:
  import_risk:
    
    name: Import risk
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Python virtual environment ( venv )
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Import risk
        env:
          ALGOSEC_SERVER: ${{ vars.ALGOSEC_SERVER }}
          ALGOSEC_USERNAME: ${{ vars.ALGOSEC_USERNAME }}
          ALGOSEC_PASSWORD: ${{ secrets.ALGOSEC_PASSWORD }}
        run: |
          source venv/bin/activate
          ./import_risk.py
