name: Import Algosec risk
on: workflow_dispatch


jobs:
  import_risk:
    name: Import risk
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute import
        run: echo ${{vars.ALGOSEC_SERVER}}