name: Import Algosec risk
on: workflow_dispatch

jobs:
  import_risk:
    name: Import risk
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create and activate Python venv
        env:
          ALGOSEC_SERVER: ${{ vars.ALGOSEC_SERVER }}
          ALGOSEC_USERNAME: ${{ vars.ALGOSEC_USERNAME }}
          ALGOSEC_PASSWORD: ${{ secrets.ALGOSEC_PASSWORD }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          set | grep ALGOSEC_
  